---
title: "R Notebook"
output: html_notebook
---

```{r}
library(challengeR)
```

Loading Processed Results

```{r}

```

```{r}
data_matrix <- read.csv("../results/preds_processed_for_challenger.csv")
data_matrix["method"][data_matrix["method"] == "FCN"] <- "MLP"

challenge <- as.challenge(data_matrix,
                          # Specify which column contains the algorithms, 
                          # which column contains a test case identifier 
                          # and which contains the metric value:
                          algorithm = "method", case = "X", value = "cross_entropy", 
                          # Specify if small metric values are better
                          smallBetter = TRUE)
```

Perform Wilcoxon signed rank test

```{r}
ranking <- challenge%>%testThenRank(alpha = 0.05, # significance level
                                    p.adjust.method = "none", # method for adjustment for
                                                              # multiple testing, see ?p.adjust
                                    na.treat = 0, # either "na.rm" to remove missing data,
                                                  # set missings to numeric value (e.g. 0)
                                                  # or specify a function, e.g. function(x) min(x)
                                    ties.method = "max" # a character string specifying
                                                        # how ties are treated, see ?base::rank
                                   )



#set.seed(1)
#ranking_bootstrapped <- ranking%>%bootstrap(nboot = 100)
#%ranking_bootstrapped %>% 
#ranking %>%
#  report(title = "singleTaskChallengeExample", # used for the title of the report
#         file = "filename", 
#         format = "HTML", # format can be "PDF", "HTML" or "Word"
#         latex_engine = "pdflatex", #LaTeX engine for producing PDF output. Options are "pdflatex", "lualatex", and "xelatex"
#         clean = TRUE #optional. Using TRUE will clean intermediate files that are created during rendering.
#        ) 
ranking
```

```{r}
ranking %>% 
  report(title = "singleTaskChallengeExample", # used for the title of the report
         file = "ranking_with_l1", 
         format = "HTML", # format can be "PDF", "HTML" or "Word"
         latex_engine = "pdflatex", #LaTeX engine for producing PDF output. Options are "pdflatex", "lualatex", and "xelatex"
         clean = FALSE #optional. Using TRUE will clean intermediate files that are created during rendering.
        )


```


```{r}
mytheme <-
  theme(
    panel.grid.major = element_line(colour = "grey", size = (0.1)),
    panel.grid.minor = element_line(
      size = (0.1), colour =
        "grey"
    ),
    panel.background = element_rect(fill='white'),
    axis.text.x=element_text(angle = -90, hjust = 0, size = rel(2)),
    axis.text.y=element_text(size = rel(2)),
    axis.title.y = element_text(size = rel(1.8), angle = 90),
    axis.title.x = element_text(size = rel(1.8)),

    legend.position="none",
    panel.border = element_rect(color = "grey",
                                    fill = NA,
                                    size = 1)
  )
boxplot(ranking , col=rgb(0,0,1)) + mytheme + ylab("Cross Entropy")
#ggsave("220923_boxplot_ranking_cross_entropy.pdf", width=12, height=8)
ggsave("220923_boxplot_ranking_cross_entropy.png")
```
